### PR TITLE
Laravel 10.x Support

### PR DESCRIPTION
**Pull request by jorbascrumps**
Me again 😄

### CODE REVIEW

**Comment by hkan** [comment]
Hi Chris! Thanks for the update. Tests are passing for L10 in local. I'll push the changes to your fork's branch and then merge it.

**Comment by hkan** [comment]
I cannot get the pipeline to work. I'll postpone this to next week. If you know what to do @jorbascrumps, feel free to give it a go. If pipelines succeed, I'm happy to merge the changes.

**Comment by jorbascrumps** [comment]
Strange that it's not working 😞 Looks like you tried to update the permissions per the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defining-access-for-the-github_token-scopes). Is it possibly a conflict with the repository settings? By [default](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions) tokens are readonly; I wonder if that setting is taking precedence?

Total shot in the dark, I haven't worked with Actions in quite a while.

**Comment by ilan-moatty** [comment]
Dealt with permissions conflicts in another [PR](https://github.com/jobilla/deprecated-routes-middleware/pull/8). I was due to some changes in the project settings (Actions)

**Comment by jorbascrumps** [comment]
Hi @ilan-moatty! Thanks for taking care of that. Are you planning to release a new version with these changes?

**Pull request closed without merging**
